// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDduGKA6XQNJmqAbIL0u_N6oyDu7fqv_X0',
    appId: '1:886678302253:android:f434a042717f5f77da92a4',
    messagingSenderId: '886678302253',
    projectId: 'chit-chat-401ec',
    storageBucket: 'chit-chat-401ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM6iaB4hKwcRkBj_L5tGh_0Kr9BEmIcjk',
    appId: '1:886678302253:ios:0f5a082cdb5d4806da92a4',
    messagingSenderId: '886678302253',
    projectId: 'chit-chat-401ec',
    storageBucket: 'chit-chat-401ec.appspot.com',
    androidClientId: '886678302253-5k3qig9cac5g6f54m7la1blspcduk9m1.apps.googleusercontent.com',
    iosClientId: '886678302253-r3091soaqfvb8rpq36tl67vgjobegu1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitChat',
  );
}
